name = "pwauth_entity"
description = "PWorks Authority DAO"
version = "0.1.0-dev"

authors = ["Sergei W Adonev"]
maintainers = ["Sergei W Adonev <admin@punks.work>"]
maintainers-logins = ["PWOAdmin"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
